name: PyPi Release

on:
    workflow_run:
        workflows: ["Create Release"]
        types: [completed]

jobs:
    pypi_package_deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - uses: actions-ecosystem/action-get-latest-tag@v1
              id: get-latest-tag

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
                  if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
            - name: Build
              env:
                  TAG: ${{ steps.get-latest-tag.outputs.tag }}
              run: |
                  git fetch --all --tags
                  git checkout tags/${TAG} -b ${TAG}
                  make dist
            - name: Publish package
              # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
              # if: startsWith(github.ref, 'refs/tags')
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
